### PR TITLE
Fix parser to merge properties of multiple sections with the same name

### PR DESCRIPTION
**Pull request by mbektchiev**
Xcode handles this correctly and some tools might produce such projects.

### CODE REVIEW

**Comment by mbektchiev** [comment]
@imhotep  Can you review and possibly merge this PR, please?

**Comment by imhotep** [comment]
Hi really sorry for the delay. Tests are not passing.

**Comment by mbektchiev** [comment]
Yes, indeed. I've fixed them and now they pass. The problem is that the check compares the strings verbatim but when there are multiple sections the files cannot be equal when merged. I've excluded the split sections project file from the verbatim checking scripts.

**Comment by imhotep** [comment]
Thanks @mbektchiev

**Pull request merged**
