### PR TITLE
Fixing bug whereby parser would fail when array entry does not have a…

### PR DESCRIPTION
**Pull request by rasharab**
… trailing comma

In our testing, we've hit projects where trailing commas are not present with array entries.

### CODE REVIEW

**Comment by imhotep** [comment]
Hey @rasharab 

The change is welcome. However, can you update your pull request to not change the name of the module nor its git repository url in package.json ?

Thanks!

**Comment by rasharab** [comment]
Doh, missed that.
Will submit it again.
Thanks.
-Rashin

**Comment by rasharab** [comment]
Updated. 
Removed that unintended commit. :)

-Rashin

**Comment by imhotep** [comment]
Merged

**Pull request closed without merging**
