### PR TITLE
Added addToOtherLinkerFlags, removeFromOtherLinkerFlags, addToBuildSettings and removeFromBuildSettings

### PR DESCRIPTION
**Pull request by IvanKarpan**

### CODE REVIEW

**Comment by imhotep** [comment]
@IvanKarpan will merge when you add in some tests for `addToOtherLinkerFlags/removeFromOtherLinkerFlags`

**Comment by IvanKarpan** [comment]
Added tests based upon HeaderSearchPaths.js, hope this is it, not a node.js/nodeunit pro... ;)

**Comment by IvanKarpan** [comment]
Added addToBuildSettings and removeFromBuildSettings

**Comment by IvanKarpan** [comment]
Can we include this? I have another request coming up, teaching the utility to add CoreData data model documents properly... Would like that to be a separate request.

**Comment by IvanKarpan** [comment]
Merged all conflicts.

**Pull request merged**
